### PR TITLE
Set window icon

### PR DESCRIPTION
**Pull request by TotalCaesar659**
This PR fixes absent icon for window.

### CODE REVIEW

**Comment by sharkwouter** [comment]
Oh, that's a cool idea. Although it doesn't quite match the icon I made for the Vita version found here: https://github.com/JoseTomasTocino/freegemas/blob/master/platform/vita/sce_sys/icon0.png

Would it be possible for you to make it match that one more?

**Comment by TotalCaesar659** [comment]
I referred to [this icon](https://github.com/JoseTomasTocino/freegemas/blob/master/media/freegemas.ico), so looks like it has to be updated too.

**Comment by sharkwouter** [comment]
Ah, I didn't realize that the icon you used wasn't new. What you could do instead is just load ``freegemas.ico`` instead. The ``IMG_Load`` function actually supports ``.ico`` files here.

**Comment by TotalCaesar659** [comment]
Are you sure? If I do this, you need to update it for Vita too for uniformity.

**Comment by sharkwouter** [comment]
Yeah, since MacOS uses that as icon for the application already I think it's fitting. I'll handle the Vita version when I do another release. It may or may not be worth changing that, but the Vita can be very finicky with how the png should be saved, otherwise it doesn't load.

**Comment by TotalCaesar659** [comment]
Got it.

**Comment by sharkwouter** [comment]
Thanks!

**Pull request merged**
